### ISSUE TITLE
v.1.7.19 dowload bug and some errors

### ISSUE THREAD

**Issue by Akrobs** [litespeedtech/openlitespeed#373] opened 2024-01-25 14:29 UTC
LS v. 1.7.19 have a bug, if download a big files. I'm using LS on several servers instances with nextcloud. After update to v 1.7.19 i have bug in download files. Revert to v 1.7.18 resume normal work

LS log:
[157942] [95.142.199.185:23342:HTTP2-1] pCache is NULL, pInfo is 0x2fd8388, pReq is 0x2fd7d08, pPath is (nil). 

[1854] [85.174.46.233:43348-Q:56EE3AEB38898796-52] pCache is NULL, pInfo is 0x2647668, pReq is 0x2646fe8, pPath is (nil). 

After revert to v 1.7.18 this lines from log is going.

**Comment by litespeedtech** [comment] 2024-01-25 15:36
1.7.19 release package has been updated last week, if you upgrade before that, please try again see if it is fixed or not.

**Comment by sbmg18** [comment] 2024-01-26 14:09
I also have this issue in the error logs: pCache is NULL.

After upgrading to the latest package (version 1.7.19-2), the frequency of the error in the logs has reduced; but, I still see these error logs for different IP addresses. The message remains the same: 'pCache is NULL,' along with other details like 'pInfo is ...' and 'pPath is (nil).'

**Comment by litespeedtech** [comment] 2024-01-26 14:58
That log message does not necessarily mean some bad happened. Do you still notice any problem? can it be reliably reproduced?

**Comment by sbmg18** [comment] 2024-01-26 15:48
I see error logs for my own IP address as well in error logs, something like what is shared above:
HTTP2-1] pCache is NULL
Q:56EE3AEB38898796-52] pCache is NULL

I don't see anything bad like something not working, it just that the logs get filled with such [ERROR] randomly, not able to reproduced reliably. When I downgrade to 1.7.18-2, there is no such log at all.

**Comment by maciek-szn** [comment] 2024-01-28 21:25
> That log message does not necessarily mean some bad happened. Do you still notice any problem? can it be reliably reproduced?

In my case this means that the user cannot download the file (PDF) as he receives a 500 error. This is not reproducible in any way, it looks like a random error.

**Comment by litespeedtech** [comment] 2024-02-06 00:43
This has been addressed in the updated 1.7.19 release today. Just download the binary package again, or, run command 
```
/usr/local/lsws/admin/misc/lsup.sh -v 1.7.19
```
to apply the fix.

**Closed** 2024-02-18 15:59 UTC
